#ifndef DATAVIEWRPT_GLOBAL_H
#define DATAVIEWRPT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DATAVIEWRPT_LIBRARY)
#  define DATAVIEWRPTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DATAVIEWRPTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DATAVIEWRPT_GLOBAL_H
