#ifndef LASTDATARPT_GLOBAL_H
#define LASTDATARPT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LASTDATARPT_LIBRARY)
#  define LASTDATARPTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LASTDATARPTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LASTDATARPT_GLOBAL_H
