#############################################################################
# Makefile for building: energo
# Generated by qmake (2.01a) (Qt 4.7.4) on: ?? 25. ??? 15:40:13 2011
# Project:  energo.pro
# Template: subdirs
# Command: c:\qt\4.7.4\bin\qmake.exe -spec c:\Qt\4.7.4\mkspecs\win32-g++ -o Makefile energo.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = c:\qt\4.7.4\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		sub-conf \
		sub-recv \
		sub-set4tm \
		sub-GSMConnection \
		sub-report \
		sub-ReportEngine

conf\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) conf\ $(MKDIR) conf\ 
	cd conf\ && $(QMAKE) d:\project\Qt\energo\conf\conf.pro -spec c:\Qt\4.7.4\mkspecs\win32-g++ -o $(MAKEFILE)
sub-conf-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) conf\ $(MKDIR) conf\ 
	cd conf\ && $(QMAKE) d:\project\Qt\energo\conf\conf.pro -spec c:\Qt\4.7.4\mkspecs\win32-g++ -o $(MAKEFILE)
sub-conf: conf\$(MAKEFILE) FORCE
	cd conf\ && $(MAKE) -f $(MAKEFILE)
sub-conf-make_default: conf\$(MAKEFILE) FORCE
	cd conf\ && $(MAKE) -f $(MAKEFILE) 
sub-conf-make_first: conf\$(MAKEFILE) FORCE
	cd conf\ && $(MAKE) -f $(MAKEFILE) first
sub-conf-all: conf\$(MAKEFILE) FORCE
	cd conf\ && $(MAKE) -f $(MAKEFILE) all
sub-conf-clean: conf\$(MAKEFILE) FORCE
	cd conf\ && $(MAKE) -f $(MAKEFILE) clean
sub-conf-distclean: conf\$(MAKEFILE) FORCE
	cd conf\ && $(MAKE) -f $(MAKEFILE) distclean
sub-conf-install_subtargets: conf\$(MAKEFILE) FORCE
	cd conf\ && $(MAKE) -f $(MAKEFILE) install
sub-conf-uninstall_subtargets: conf\$(MAKEFILE) FORCE
	cd conf\ && $(MAKE) -f $(MAKEFILE) uninstall
recv\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) recv\ $(MKDIR) recv\ 
	cd recv\ && $(QMAKE) d:\project\Qt\energo\recv\recv.pro -spec c:\Qt\4.7.4\mkspecs\win32-g++ -o $(MAKEFILE)
sub-recv-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) recv\ $(MKDIR) recv\ 
	cd recv\ && $(QMAKE) d:\project\Qt\energo\recv\recv.pro -spec c:\Qt\4.7.4\mkspecs\win32-g++ -o $(MAKEFILE)
sub-recv: recv\$(MAKEFILE) FORCE
	cd recv\ && $(MAKE) -f $(MAKEFILE)
sub-recv-make_default: recv\$(MAKEFILE) FORCE
	cd recv\ && $(MAKE) -f $(MAKEFILE) 
sub-recv-make_first: recv\$(MAKEFILE) FORCE
	cd recv\ && $(MAKE) -f $(MAKEFILE) first
sub-recv-all: recv\$(MAKEFILE) FORCE
	cd recv\ && $(MAKE) -f $(MAKEFILE) all
sub-recv-clean: recv\$(MAKEFILE) FORCE
	cd recv\ && $(MAKE) -f $(MAKEFILE) clean
sub-recv-distclean: recv\$(MAKEFILE) FORCE
	cd recv\ && $(MAKE) -f $(MAKEFILE) distclean
sub-recv-install_subtargets: recv\$(MAKEFILE) FORCE
	cd recv\ && $(MAKE) -f $(MAKEFILE) install
sub-recv-uninstall_subtargets: recv\$(MAKEFILE) FORCE
	cd recv\ && $(MAKE) -f $(MAKEFILE) uninstall
set4tm\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) set4tm\ $(MKDIR) set4tm\ 
	cd set4tm\ && $(QMAKE) d:\project\Qt\energo\set4tm\set4tm.pro -spec c:\Qt\4.7.4\mkspecs\win32-g++ -o $(MAKEFILE)
sub-set4tm-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) set4tm\ $(MKDIR) set4tm\ 
	cd set4tm\ && $(QMAKE) d:\project\Qt\energo\set4tm\set4tm.pro -spec c:\Qt\4.7.4\mkspecs\win32-g++ -o $(MAKEFILE)
sub-set4tm: set4tm\$(MAKEFILE) FORCE
	cd set4tm\ && $(MAKE) -f $(MAKEFILE)
sub-set4tm-make_default: set4tm\$(MAKEFILE) FORCE
	cd set4tm\ && $(MAKE) -f $(MAKEFILE) 
sub-set4tm-make_first: set4tm\$(MAKEFILE) FORCE
	cd set4tm\ && $(MAKE) -f $(MAKEFILE) first
sub-set4tm-all: set4tm\$(MAKEFILE) FORCE
	cd set4tm\ && $(MAKE) -f $(MAKEFILE) all
sub-set4tm-clean: set4tm\$(MAKEFILE) FORCE
	cd set4tm\ && $(MAKE) -f $(MAKEFILE) clean
sub-set4tm-distclean: set4tm\$(MAKEFILE) FORCE
	cd set4tm\ && $(MAKE) -f $(MAKEFILE) distclean
sub-set4tm-install_subtargets: set4tm\$(MAKEFILE) FORCE
	cd set4tm\ && $(MAKE) -f $(MAKEFILE) install
sub-set4tm-uninstall_subtargets: set4tm\$(MAKEFILE) FORCE
	cd set4tm\ && $(MAKE) -f $(MAKEFILE) uninstall
GSMConnection\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) GSMConnection\ $(MKDIR) GSMConnection\ 
	cd GSMConnection\ && $(QMAKE) d:\project\Qt\energo\GSMConnection\GSMConnection.pro -spec c:\Qt\4.7.4\mkspecs\win32-g++ -o $(MAKEFILE)
sub-GSMConnection-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) GSMConnection\ $(MKDIR) GSMConnection\ 
	cd GSMConnection\ && $(QMAKE) d:\project\Qt\energo\GSMConnection\GSMConnection.pro -spec c:\Qt\4.7.4\mkspecs\win32-g++ -o $(MAKEFILE)
sub-GSMConnection: GSMConnection\$(MAKEFILE) FORCE
	cd GSMConnection\ && $(MAKE) -f $(MAKEFILE)
sub-GSMConnection-make_default: GSMConnection\$(MAKEFILE) FORCE
	cd GSMConnection\ && $(MAKE) -f $(MAKEFILE) 
sub-GSMConnection-make_first: GSMConnection\$(MAKEFILE) FORCE
	cd GSMConnection\ && $(MAKE) -f $(MAKEFILE) first
sub-GSMConnection-all: GSMConnection\$(MAKEFILE) FORCE
	cd GSMConnection\ && $(MAKE) -f $(MAKEFILE) all
sub-GSMConnection-clean: GSMConnection\$(MAKEFILE) FORCE
	cd GSMConnection\ && $(MAKE) -f $(MAKEFILE) clean
sub-GSMConnection-distclean: GSMConnection\$(MAKEFILE) FORCE
	cd GSMConnection\ && $(MAKE) -f $(MAKEFILE) distclean
sub-GSMConnection-install_subtargets: GSMConnection\$(MAKEFILE) FORCE
	cd GSMConnection\ && $(MAKE) -f $(MAKEFILE) install
sub-GSMConnection-uninstall_subtargets: GSMConnection\$(MAKEFILE) FORCE
	cd GSMConnection\ && $(MAKE) -f $(MAKEFILE) uninstall
report\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) report\ $(MKDIR) report\ 
	cd report\ && $(QMAKE) d:\project\Qt\energo\report\report.pro -spec c:\Qt\4.7.4\mkspecs\win32-g++ -o $(MAKEFILE)
sub-report-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) report\ $(MKDIR) report\ 
	cd report\ && $(QMAKE) d:\project\Qt\energo\report\report.pro -spec c:\Qt\4.7.4\mkspecs\win32-g++ -o $(MAKEFILE)
sub-report: report\$(MAKEFILE) FORCE
	cd report\ && $(MAKE) -f $(MAKEFILE)
sub-report-make_default: report\$(MAKEFILE) FORCE
	cd report\ && $(MAKE) -f $(MAKEFILE) 
sub-report-make_first: report\$(MAKEFILE) FORCE
	cd report\ && $(MAKE) -f $(MAKEFILE) first
sub-report-all: report\$(MAKEFILE) FORCE
	cd report\ && $(MAKE) -f $(MAKEFILE) all
sub-report-clean: report\$(MAKEFILE) FORCE
	cd report\ && $(MAKE) -f $(MAKEFILE) clean
sub-report-distclean: report\$(MAKEFILE) FORCE
	cd report\ && $(MAKE) -f $(MAKEFILE) distclean
sub-report-install_subtargets: report\$(MAKEFILE) FORCE
	cd report\ && $(MAKE) -f $(MAKEFILE) install
sub-report-uninstall_subtargets: report\$(MAKEFILE) FORCE
	cd report\ && $(MAKE) -f $(MAKEFILE) uninstall
ReportEngine\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) ReportEngine\ $(MKDIR) ReportEngine\ 
	cd ReportEngine\ && $(QMAKE) d:\project\Qt\energo\ReportEngine\ReportEngine.pro -spec c:\Qt\4.7.4\mkspecs\win32-g++ -o $(MAKEFILE)
sub-ReportEngine-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) ReportEngine\ $(MKDIR) ReportEngine\ 
	cd ReportEngine\ && $(QMAKE) d:\project\Qt\energo\ReportEngine\ReportEngine.pro -spec c:\Qt\4.7.4\mkspecs\win32-g++ -o $(MAKEFILE)
sub-ReportEngine: ReportEngine\$(MAKEFILE) FORCE
	cd ReportEngine\ && $(MAKE) -f $(MAKEFILE)
sub-ReportEngine-make_default: ReportEngine\$(MAKEFILE) FORCE
	cd ReportEngine\ && $(MAKE) -f $(MAKEFILE) 
sub-ReportEngine-make_first: ReportEngine\$(MAKEFILE) FORCE
	cd ReportEngine\ && $(MAKE) -f $(MAKEFILE) first
sub-ReportEngine-all: ReportEngine\$(MAKEFILE) FORCE
	cd ReportEngine\ && $(MAKE) -f $(MAKEFILE) all
sub-ReportEngine-clean: ReportEngine\$(MAKEFILE) FORCE
	cd ReportEngine\ && $(MAKE) -f $(MAKEFILE) clean
sub-ReportEngine-distclean: ReportEngine\$(MAKEFILE) FORCE
	cd ReportEngine\ && $(MAKE) -f $(MAKEFILE) distclean
sub-ReportEngine-install_subtargets: ReportEngine\$(MAKEFILE) FORCE
	cd ReportEngine\ && $(MAKE) -f $(MAKEFILE) install
sub-ReportEngine-uninstall_subtargets: ReportEngine\$(MAKEFILE) FORCE
	cd ReportEngine\ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: energo.pro  c:/Qt/4.7.4/mkspecs/win32-g++/qmake.conf c:/Qt/4.7.4/mkspecs/qconfig.pri \
		c:/Qt/4.7.4/mkspecs/modules/qt_webkit_version.pri \
		c:/Qt/4.7.4/mkspecs/features/qt_functions.prf \
		c:/Qt/4.7.4/mkspecs/features/qt_config.prf \
		c:/Qt/4.7.4/mkspecs/features/exclusive_builds.prf \
		c:/Qt/4.7.4/mkspecs/features/default_pre.prf \
		c:/Qt/4.7.4/mkspecs/features/win32/default_pre.prf \
		c:/Qt/4.7.4/mkspecs/features/debug.prf \
		c:/Qt/4.7.4/mkspecs/features/debug_and_release.prf \
		c:/Qt/4.7.4/mkspecs/features/default_post.prf \
		c:/Qt/4.7.4/mkspecs/features/win32/default_post.prf \
		c:/Qt/4.7.4/mkspecs/features/win32/rtti.prf \
		c:/Qt/4.7.4/mkspecs/features/win32/exceptions.prf \
		c:/Qt/4.7.4/mkspecs/features/win32/stl.prf \
		c:/Qt/4.7.4/mkspecs/features/shared.prf \
		c:/Qt/4.7.4/mkspecs/features/warn_on.prf \
		c:/Qt/4.7.4/mkspecs/features/qt.prf \
		c:/Qt/4.7.4/mkspecs/features/win32/thread.prf \
		c:/Qt/4.7.4/mkspecs/features/moc.prf \
		c:/Qt/4.7.4/mkspecs/features/win32/windows.prf \
		c:/Qt/4.7.4/mkspecs/features/resources.prf \
		c:/Qt/4.7.4/mkspecs/features/uic.prf \
		c:/Qt/4.7.4/mkspecs/features/yacc.prf \
		c:/Qt/4.7.4/mkspecs/features/lex.prf \
		c:/Qt/4.7.4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec c:\Qt\4.7.4\mkspecs\win32-g++ -o Makefile energo.pro
c:\Qt\4.7.4\mkspecs\qconfig.pri:
c:\Qt\4.7.4\mkspecs\modules\qt_webkit_version.pri:
c:\Qt\4.7.4\mkspecs\features\qt_functions.prf:
c:\Qt\4.7.4\mkspecs\features\qt_config.prf:
c:\Qt\4.7.4\mkspecs\features\exclusive_builds.prf:
c:\Qt\4.7.4\mkspecs\features\default_pre.prf:
c:\Qt\4.7.4\mkspecs\features\win32\default_pre.prf:
c:\Qt\4.7.4\mkspecs\features\debug.prf:
c:\Qt\4.7.4\mkspecs\features\debug_and_release.prf:
c:\Qt\4.7.4\mkspecs\features\default_post.prf:
c:\Qt\4.7.4\mkspecs\features\win32\default_post.prf:
c:\Qt\4.7.4\mkspecs\features\win32\rtti.prf:
c:\Qt\4.7.4\mkspecs\features\win32\exceptions.prf:
c:\Qt\4.7.4\mkspecs\features\win32\stl.prf:
c:\Qt\4.7.4\mkspecs\features\shared.prf:
c:\Qt\4.7.4\mkspecs\features\warn_on.prf:
c:\Qt\4.7.4\mkspecs\features\qt.prf:
c:\Qt\4.7.4\mkspecs\features\win32\thread.prf:
c:\Qt\4.7.4\mkspecs\features\moc.prf:
c:\Qt\4.7.4\mkspecs\features\win32\windows.prf:
c:\Qt\4.7.4\mkspecs\features\resources.prf:
c:\Qt\4.7.4\mkspecs\features\uic.prf:
c:\Qt\4.7.4\mkspecs\features\yacc.prf:
c:\Qt\4.7.4\mkspecs\features\lex.prf:
c:\Qt\4.7.4\mkspecs\features\include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec c:\Qt\4.7.4\mkspecs\win32-g++ -o Makefile energo.pro

qmake_all: sub-conf-qmake_all sub-recv-qmake_all sub-set4tm-qmake_all sub-GSMConnection-qmake_all sub-report-qmake_all sub-ReportEngine-qmake_all FORCE

make_default: sub-conf-make_default sub-recv-make_default sub-set4tm-make_default sub-GSMConnection-make_default sub-report-make_default sub-ReportEngine-make_default FORCE
make_first: sub-conf-make_first sub-recv-make_first sub-set4tm-make_first sub-GSMConnection-make_first sub-report-make_first sub-ReportEngine-make_first FORCE
all: sub-conf-all sub-recv-all sub-set4tm-all sub-GSMConnection-all sub-report-all sub-ReportEngine-all FORCE
clean: sub-conf-clean sub-recv-clean sub-set4tm-clean sub-GSMConnection-clean sub-report-clean sub-ReportEngine-clean FORCE
distclean: sub-conf-distclean sub-recv-distclean sub-set4tm-distclean sub-GSMConnection-distclean sub-report-distclean sub-ReportEngine-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-conf-install_subtargets sub-recv-install_subtargets sub-set4tm-install_subtargets sub-GSMConnection-install_subtargets sub-report-install_subtargets sub-ReportEngine-install_subtargets FORCE
uninstall_subtargets: sub-conf-uninstall_subtargets sub-recv-uninstall_subtargets sub-set4tm-uninstall_subtargets sub-GSMConnection-uninstall_subtargets sub-report-uninstall_subtargets sub-ReportEngine-uninstall_subtargets FORCE

sub-conf-sub_Debug: conf\$(MAKEFILE)
	cd conf\ && $(MAKE) debug
sub-recv-sub_Debug: recv\$(MAKEFILE)
	cd recv\ && $(MAKE) debug
sub-set4tm-sub_Debug: set4tm\$(MAKEFILE)
	cd set4tm\ && $(MAKE) debug
sub-GSMConnection-sub_Debug: GSMConnection\$(MAKEFILE)
	cd GSMConnection\ && $(MAKE) debug
sub-report-sub_Debug: report\$(MAKEFILE)
	cd report\ && $(MAKE) debug
sub-ReportEngine-sub_Debug: ReportEngine\$(MAKEFILE)
	cd ReportEngine\ && $(MAKE) debug
debug: sub-conf-sub_Debug sub-recv-sub_Debug sub-set4tm-sub_Debug sub-GSMConnection-sub_Debug sub-report-sub_Debug sub-ReportEngine-sub_Debug

sub-conf-sub_Release: conf\$(MAKEFILE)
	cd conf\ && $(MAKE) release
sub-recv-sub_Release: recv\$(MAKEFILE)
	cd recv\ && $(MAKE) release
sub-set4tm-sub_Release: set4tm\$(MAKEFILE)
	cd set4tm\ && $(MAKE) release
sub-GSMConnection-sub_Release: GSMConnection\$(MAKEFILE)
	cd GSMConnection\ && $(MAKE) release
sub-report-sub_Release: report\$(MAKEFILE)
	cd report\ && $(MAKE) release
sub-ReportEngine-sub_Release: ReportEngine\$(MAKEFILE)
	cd ReportEngine\ && $(MAKE) release
release: sub-conf-sub_Release sub-recv-sub_Release sub-set4tm-sub_Release sub-GSMConnection-sub_Release sub-report-sub_Release sub-ReportEngine-sub_Release

sub-conf-check: conf\$(MAKEFILE)
	cd conf\ && $(MAKE) check
sub-recv-check: recv\$(MAKEFILE)
	cd recv\ && $(MAKE) check
sub-set4tm-check: set4tm\$(MAKEFILE)
	cd set4tm\ && $(MAKE) check
sub-GSMConnection-check: GSMConnection\$(MAKEFILE)
	cd GSMConnection\ && $(MAKE) check
sub-report-check: report\$(MAKEFILE)
	cd report\ && $(MAKE) check
sub-ReportEngine-check: ReportEngine\$(MAKEFILE)
	cd ReportEngine\ && $(MAKE) check
check: sub-conf-check sub-recv-check sub-set4tm-check sub-GSMConnection-check sub-report-check sub-ReportEngine-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

