#ifndef ALERTVIEWRPT_GLOBAL_H
#define ALERTVIEWRPT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ALERTVIEWRPT_LIBRARY)
#  define ALERTVIEWRPTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ALERTVIEWRPTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ALERTVIEWRPT_GLOBAL_H
