#ifndef REGISTERRPT_GLOBAL_H
#define REGISTERRPT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(REGISTERRPT_LIBRARY)
#  define REGISTERRPTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define REGISTERRPTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // REGISTERRPT_GLOBAL_H
