#ifndef ONESEXPORTRPT_GLOBAL_H
#define ONESEXPORTRPT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ONESEXPORTRPT_LIBRARY)
#  define ONESEXPORTRPTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ONESEXPORTRPTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ONESEXPORTRPT_GLOBAL_H
