#ifndef MANUALINPUTRPT_GLOBAL_H
#define MANUALINPUTRPT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MANUALINPUTRPT_LIBRARY)
#  define MANUALINPUTRPTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MANUALINPUTRPTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MANUALINPUTRPT_GLOBAL_H
