#ifndef CHECKDATARPT_GLOBAL_H
#define CHECKDATARPT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CHECKDATARPT_LIBRARY)
#  define CHECKDATARPTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CHECKDATARPTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CHECKDATARPT_GLOBAL_H
