#ifndef REPORTENGINE_GLOBAL_H
#define REPORTENGINE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(REPORTENGINE_LIBRARY)
#  define REPORTENGINESHARED_EXPORT Q_DECL_EXPORT
#else
#  define REPORTENGINESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // REPORTENGINE_GLOBAL_H
